#!/bin/bash -e

CURRENT_VERSION="$(git describe --tags || echo "v1.0.0")"
export VITE_PRACTICE_VERSION="$(echo $CURRENT_VERSION | awk -F. -v OFS=. '{$(NF-1) += 1 ; print}')"
echo "New version: $VITE_PRACTICE_VERSION"

git tag "$VITE_PRACTICE_VERSION"
